version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - visionary_network


  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - visionary_network

networks:
  visionary_network:
    driver: bridge